name: leapfrog-assignment-container
# version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: leapfrog-assignment-db
    environment:
      POSTGRES_USER: sachyamdh
      POSTGRES_PASSWORD: leapfrog
      POSTGRES_DB: note_app_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
