openapi: 3.0.4
info:
  title: Note App API
  description: API documentation for the Note App
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /api/v1/health:
    get:
      summary: Health check
      description: Check if the API is running
      tags:
        - Health
      responses:
        "200":
          description: API is running
        "500":
          description: Internal server error
  /api/v1/auth/signup:
    post:
      summary: Register a new user account
      tags:
        - Authentication
      description: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - userName
                - email
                - password
                - confirmPassword
              properties:
                firstName:
                  type: string
                  example: Alex
                  minLength: 3
                  maxLength: 20
                lastName:
                  type: string
                  example: Wozniak
                  minLength: 3
                  maxLength: 20
                userName:
                  type: string
                  example: AlexWo
                  minLength: 3
                  maxLength: 20
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  minLength: 6
                  example: "Str0ngP@ssword"
                confirmPassword:
                  type: string
                  format: password
                  minLength: 6
                  example: "Str0ngP@ssword"
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      email:
                        type: string
        400:
          description: |
            Bad request. Possible reasons:
            - Missing required fields
            - Invalid email format
            - Password too short
            - Passwords do not match
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid data format"
        409:
          description: Email already registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Email already in use"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Could not create user"
