import type { Metadata } from "next";
// import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Source_Sans_3 } from "next/font/google";
import "@/src/styles/global.scss";
import { Navbar } from "@/src/components/organisms/navbars";
import { AuthProvider } from "../contexts/AuthContext";

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceSans.variable} antialiased m-0 p-0`}>
        <AuthProvider>
          {/* <AppRouterCacheProvider> */}
          <Navbar />
          {children}
          {/* </AppRouterCacheProvider> */}
        </AuthProvider>
      </body>
    </html>
  );
}
